create table private.legacy_v1_import_batches (
    id bigint generated by default as identity primary key,
    source_exported_at timestamptz not null,
    created_at timestamptz not null default clock_timestamp(),
    classified_at timestamptz null,
    promoted_at timestamptz null
);

create table private.legacy_v1_items (
    batch_id bigint not null references private.legacy_v1_import_batches(id) on delete cascade,
    id bigint not null,
    name text not null,
    base_price_cents bigint not null,
    is_active boolean not null,
    category_id bigint null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    primary key (batch_id, id),
    constraint legacy_v1_items_id_positive check (id > 0),
    constraint legacy_v1_items_name_not_blank check (btrim(name) <> ''),
    constraint legacy_v1_items_price_positive check (base_price_cents > 0),
    constraint legacy_v1_items_normalized_active_unclassified check (is_active and category_id is null),
    constraint legacy_v1_items_timestamp_order check (updated_at >= created_at)
);

create table private.legacy_v1_resellers (
    batch_id bigint not null references private.legacy_v1_import_batches(id) on delete cascade,
    id bigint not null,
    name text not null,
    phone text null,
    email text null,
    notes text null,
    is_active boolean not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    primary key (batch_id, id),
    constraint legacy_v1_resellers_id_positive check (id > 0),
    constraint legacy_v1_resellers_name_not_blank check (btrim(name) <> ''),
    constraint legacy_v1_resellers_normalized_active check (is_active),
    constraint legacy_v1_resellers_timestamp_order check (updated_at >= created_at)
);

create table private.legacy_v1_transactions (
    batch_id bigint not null references private.legacy_v1_import_batches(id) on delete cascade,
    id bigint not null,
    reseller_id bigint not null,
    type text not null,
    item_id bigint null,
    item_name text null,
    quantity integer null,
    unit_price_cents bigint null,
    total_price_cents bigint not null,
    observation text null,
    category_id bigint null,
    category_name text null,
    reversal_reason text null,
    reversed_at timestamptz null,
    replacement_transaction_id bigint null,
    replaces_transaction_id bigint null,
    occurred_at timestamptz not null,
    created_at timestamptz not null,
    primary key (batch_id, id),
    constraint legacy_v1_transactions_reseller_fk
        foreign key (batch_id, reseller_id)
        references private.legacy_v1_resellers(batch_id, id)
        on delete cascade,
    constraint legacy_v1_transactions_item_fk
        foreign key (batch_id, item_id)
        references private.legacy_v1_items(batch_id, id)
        on delete cascade,
    constraint legacy_v1_transactions_id_positive check (id > 0),
    constraint legacy_v1_transactions_total_positive check (total_price_cents > 0),
    constraint legacy_v1_transactions_type_valid check (type in ('order', 'payment', 'signal')),
    constraint legacy_v1_transactions_occurrence_matches_created check (occurred_at = created_at),
    constraint legacy_v1_transactions_no_v2_history check (
        category_id is null
        and category_name is null
        and reversal_reason is null
        and reversed_at is null
        and replacement_transaction_id is null
        and replaces_transaction_id is null
    ),
    constraint legacy_v1_transactions_shape_valid check (
        (
            type = 'order'
            and item_id is not null
            and item_name is not null
            and btrim(item_name) <> ''
            and quantity is not null
            and quantity > 0
            and unit_price_cents is not null
            and unit_price_cents > 0
            and total_price_cents = quantity::bigint * unit_price_cents
        )
        or
        (
            type in ('payment', 'signal')
            and item_id is null
            and item_name is null
            and quantity is null
            and unit_price_cents is null
        )
    )
);

create table private.legacy_v1_item_classifications (
    batch_id bigint not null,
    item_id bigint not null,
    category_name text not null,
    primary key (batch_id, item_id),
    constraint legacy_v1_item_classifications_item_fk
        foreign key (batch_id, item_id)
        references private.legacy_v1_items(batch_id, id)
        on delete cascade,
    constraint legacy_v1_item_classification_name_valid check (
        btrim(category_name) <> '' and category_name = btrim(category_name)
    )
);

alter table private.legacy_v1_import_batches enable row level security;
alter table private.legacy_v1_items enable row level security;
alter table private.legacy_v1_resellers enable row level security;
alter table private.legacy_v1_transactions enable row level security;
alter table private.legacy_v1_item_classifications enable row level security;

revoke all on table private.legacy_v1_import_batches from public, anon, authenticated, service_role;
revoke all on table private.legacy_v1_items from public, anon, authenticated, service_role;
revoke all on table private.legacy_v1_resellers from public, anon, authenticated, service_role;
revoke all on table private.legacy_v1_transactions from public, anon, authenticated, service_role;
revoke all on table private.legacy_v1_item_classifications from public, anon, authenticated, service_role;

create or replace function private.jsonb_has_exact_keys(
    p_value jsonb,
    p_keys text[]
)
returns boolean
language sql
immutable
security invoker
set search_path = ''
as $$
    select
        pg_catalog.jsonb_typeof(p_value) = 'object'
        and coalesce(
            (select pg_catalog.array_agg(k order by k) from pg_catalog.jsonb_object_keys(p_value) as actual(k)),
            array[]::text[]
        ) = coalesce(
            (select pg_catalog.array_agg(k order by k) from pg_catalog.unnest(p_keys) as expected(k)),
            array[]::text[]
        );
$$;

create or replace function private.stage_legacy_v1_normalized(p_payload jsonb)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_batch_id bigint;
    v_exported_at timestamptz;
begin
    if not private.jsonb_has_exact_keys(
        p_payload,
        array['exportedAt', 'items', 'resellers', 'sourceVersion', 'transactions']
    ) then
        raise exception using errcode = '22023', message = 'Payload normalizado v1 possui estrutura raiz inválida.';
    end if;

    if pg_catalog.jsonb_typeof(p_payload -> 'sourceVersion') <> 'number'
       or (p_payload ->> 'sourceVersion') <> '1'
    then
        raise exception using errcode = '22023', message = 'Somente sourceVersion 1 pode entrar no staging legado.';
    end if;

    if pg_catalog.jsonb_typeof(p_payload -> 'exportedAt') <> 'string' then
        raise exception using errcode = '22023', message = 'exportedAt deve ser uma data serializada como texto.';
    end if;

    begin
        v_exported_at := (p_payload ->> 'exportedAt')::timestamptz;
    exception
        when others then
            raise exception using errcode = '22007', message = 'exportedAt inválido no payload normalizado v1.';
    end;

    if pg_catalog.jsonb_typeof(p_payload -> 'items') <> 'array'
       or pg_catalog.jsonb_typeof(p_payload -> 'resellers') <> 'array'
       or pg_catalog.jsonb_typeof(p_payload -> 'transactions') <> 'array'
    then
        raise exception using errcode = '22023', message = 'items, resellers e transactions devem ser arrays.';
    end if;

    if exists (
        select 1
        from pg_catalog.jsonb_array_elements(p_payload -> 'items') as row_value
        where not private.jsonb_has_exact_keys(
            row_value,
            array['basePriceCents', 'categoryId', 'createdAt', 'id', 'isActive', 'name', 'updatedAt']
        )
    ) then
        raise exception using errcode = '22023', message = 'Item de staging contém campos ausentes ou não aceitos.';
    end if;

    if exists (
        select 1
        from pg_catalog.jsonb_array_elements(p_payload -> 'items') as row_value
        where row_value -> 'isActive' <> 'true'::jsonb
           or row_value -> 'categoryId' <> 'null'::jsonb
    ) then
        raise exception using errcode = '22023', message = 'Item v1 normalizado deve estar ativo e sem categoria no staging.';
    end if;

    if exists (
        select 1
        from pg_catalog.jsonb_array_elements(p_payload -> 'resellers') as row_value
        where not private.jsonb_has_exact_keys(
            row_value,
            array['createdAt', 'email', 'id', 'isActive', 'name', 'notes', 'phone', 'updatedAt']
        )
    ) then
        raise exception using errcode = '22023', message = 'Revendedor de staging contém campos ausentes ou não aceitos.';
    end if;

    if exists (
        select 1
        from pg_catalog.jsonb_array_elements(p_payload -> 'resellers') as row_value
        where row_value -> 'isActive' <> 'true'::jsonb
    ) then
        raise exception using errcode = '22023', message = 'Revendedor v1 normalizado deve estar ativo no staging.';
    end if;

    if exists (
        select 1
        from pg_catalog.jsonb_array_elements(p_payload -> 'transactions') as row_value
        where not private.jsonb_has_exact_keys(
            row_value,
            array[
                'categoryId', 'categoryName', 'correction', 'createdAt', 'id',
                'itemId', 'itemName', 'observation', 'occurredAt', 'quantity',
                'resellerId', 'reversal', 'totalPriceCents', 'type', 'unitPriceCents'
            ]
        )
    ) then
        raise exception using errcode = '22023', message = 'Lançamento de staging contém campos ausentes ou não aceitos.';
    end if;

    if exists (
        select 1
        from pg_catalog.jsonb_array_elements(p_payload -> 'transactions') as row_value
        where row_value -> 'categoryId' <> 'null'::jsonb
           or row_value -> 'categoryName' <> 'null'::jsonb
           or row_value -> 'reversal' <> 'null'::jsonb
           or row_value -> 'correction' <> 'null'::jsonb
    ) then
        raise exception using errcode = '22023', message = 'Histórico v1 não pode fabricar categoria, reversão ou correção.';
    end if;

    insert into private.legacy_v1_import_batches(source_exported_at)
    values (v_exported_at)
    returning id into v_batch_id;

    insert into private.legacy_v1_items(
        batch_id, id, name, base_price_cents, is_active, category_id, created_at, updated_at
    )
    select
        v_batch_id,
        row_value."id",
        row_value."name",
        row_value."basePriceCents",
        row_value."isActive",
        row_value."categoryId",
        row_value."createdAt",
        row_value."updatedAt"
    from pg_catalog.jsonb_to_recordset(p_payload -> 'items') as row_value(
        "id" bigint,
        "name" text,
        "basePriceCents" bigint,
        "isActive" boolean,
        "categoryId" bigint,
        "createdAt" timestamptz,
        "updatedAt" timestamptz
    );

    insert into private.legacy_v1_resellers(
        batch_id, id, name, phone, email, notes, is_active, created_at, updated_at
    )
    select
        v_batch_id,
        row_value."id",
        row_value."name",
        row_value."phone",
        row_value."email",
        row_value."notes",
        row_value."isActive",
        row_value."createdAt",
        row_value."updatedAt"
    from pg_catalog.jsonb_to_recordset(p_payload -> 'resellers') as row_value(
        "id" bigint,
        "name" text,
        "phone" text,
        "email" text,
        "notes" text,
        "isActive" boolean,
        "createdAt" timestamptz,
        "updatedAt" timestamptz
    );

    insert into private.legacy_v1_transactions(
        batch_id, id, reseller_id, type, item_id, item_name, quantity,
        unit_price_cents, total_price_cents, observation,
        category_id, category_name, reversal_reason, reversed_at,
        replacement_transaction_id, replaces_transaction_id,
        occurred_at, created_at
    )
    select
        v_batch_id,
        row_value."id",
        row_value."resellerId",
        row_value."type",
        row_value."itemId",
        row_value."itemName",
        row_value."quantity",
        row_value."unitPriceCents",
        row_value."totalPriceCents",
        row_value."observation",
        null,
        null,
        null,
        null,
        null,
        null,
        row_value."occurredAt",
        row_value."createdAt"
    from pg_catalog.jsonb_to_recordset(p_payload -> 'transactions') as row_value(
        "id" bigint,
        "resellerId" bigint,
        "type" text,
        "itemId" bigint,
        "itemName" text,
        "quantity" integer,
        "unitPriceCents" bigint,
        "totalPriceCents" bigint,
        "observation" text,
        "categoryId" bigint,
        "categoryName" text,
        "reversal" jsonb,
        "correction" jsonb,
        "occurredAt" timestamptz,
        "createdAt" timestamptz
    );

    return v_batch_id;
end;
$$;

create or replace function private.set_legacy_v1_classifications(
    p_batch_id bigint,
    p_classifications jsonb
)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_expected integer;
    v_actual integer;
    v_promoted_at timestamptz;
begin
    select b.promoted_at
      into v_promoted_at
      from private.legacy_v1_import_batches b
     where b.id = p_batch_id
     for update;

    if not found then
        raise exception using errcode = 'P0002', message = 'Lote de staging legado não encontrado.';
    end if;

    if v_promoted_at is not null then
        raise exception using errcode = '23514', message = 'Lote já promovido não pode ser reclassificado.';
    end if;

    if pg_catalog.jsonb_typeof(p_classifications) <> 'array' then
        raise exception using errcode = '22023', message = 'Classificações devem ser um array.';
    end if;

    if exists (
        select 1
        from pg_catalog.jsonb_array_elements(p_classifications) as row_value
        where not private.jsonb_has_exact_keys(row_value, array['categoryName', 'itemId'])
    ) then
        raise exception using errcode = '22023', message = 'Classificação contém campos ausentes ou não aceitos.';
    end if;

    delete from private.legacy_v1_item_classifications
     where batch_id = p_batch_id;

    insert into private.legacy_v1_item_classifications(batch_id, item_id, category_name)
    select
        p_batch_id,
        row_value."itemId",
        row_value."categoryName"
    from pg_catalog.jsonb_to_recordset(p_classifications) as row_value(
        "itemId" bigint,
        "categoryName" text
    );

    if exists (
        select 1
          from private.legacy_v1_item_classifications c
         where c.batch_id = p_batch_id
         group by lower(c.category_name)
        having count(distinct c.category_name) > 1
    ) then
        raise exception using errcode = '23505', message = 'Nomes de categoria logicamente iguais devem usar a mesma grafia.';
    end if;

    select count(*)::integer
      into v_expected
      from private.legacy_v1_items i
     where i.batch_id = p_batch_id
       and i.is_active;

    select count(*)::integer
      into v_actual
      from private.legacy_v1_item_classifications c
     where c.batch_id = p_batch_id;

    if v_actual <> v_expected then
        raise exception using
            errcode = '23514',
            message = 'Todo item legado ativo deve possuir classificação atual explícita antes da promoção.';
    end if;

    update private.legacy_v1_import_batches
       set classified_at = clock_timestamp()
     where id = p_batch_id;

    return v_actual;
end;
$$;

create or replace function private.repair_identity_sequence(
    p_table regclass,
    p_column name
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_sequence text;
    v_max bigint;
begin
    v_sequence := pg_catalog.pg_get_serial_sequence(p_table::text, p_column::text);
    if v_sequence is null then
        raise exception using errcode = '55000', message = 'Sequência identity não encontrada por metadados.';
    end if;

    execute pg_catalog.format('select max(%I)::bigint from %s', p_column, p_table)
       into v_max;

    if v_max is null then
        perform pg_catalog.setval(v_sequence::regclass, 1, false);
        return 1;
    end if;

    perform pg_catalog.setval(v_sequence::regclass, v_max, true);
    return v_max + 1;
end;
$$;

create or replace function private.identity_sequence_is_ahead(
    p_table regclass,
    p_column name
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_sequence text;
    v_max bigint;
    v_last bigint;
    v_called boolean;
    v_increment bigint;
    v_next numeric;
begin
    v_sequence := pg_catalog.pg_get_serial_sequence(p_table::text, p_column::text);
    if v_sequence is null then
        return false;
    end if;

    execute pg_catalog.format('select max(%I)::bigint from %s', p_column, p_table)
       into v_max;

    execute pg_catalog.format('select last_value::bigint, is_called from %s', v_sequence::regclass)
       into v_last, v_called;

    select s.seqincrement
      into v_increment
      from pg_catalog.pg_sequence s
     where s.seqrelid = v_sequence::regclass;

    v_next := case when v_called then v_last::numeric + v_increment else v_last::numeric end;
    return v_max is null or v_next > v_max;
end;
$$;

create or replace function private.reconcile_legacy_v1_import(p_batch_id bigint)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_source_items bigint;
    v_source_resellers bigint;
    v_source_transactions bigint;
    v_target_items bigint;
    v_target_resellers bigint;
    v_target_transactions bigint;
    v_source_orders bigint;
    v_source_payments bigint;
    v_source_signals bigint;
    v_target_orders bigint;
    v_target_payments bigint;
    v_target_signals bigint;
    v_expected_categories bigint;
    v_target_categories bigint;
    v_items_match boolean;
    v_resellers_match boolean;
    v_transactions_match boolean;
    v_categories_match boolean;
    v_references_match boolean;
    v_history_clean boolean;
    v_sequences_ahead boolean;
    v_source_gross bigint;
    v_source_payments_value bigint;
    v_source_signals_value bigint;
    v_source_net bigint;
    v_source_positive_debt bigint;
    v_target_gross bigint;
    v_target_payments_value bigint;
    v_target_signals_value bigint;
    v_target_net bigint;
    v_target_positive_debt bigint;
    v_balances_match boolean;
    v_financial_match boolean;
    v_passed boolean;
begin
    if not exists (
        select 1 from private.legacy_v1_import_batches b where b.id = p_batch_id
    ) then
        raise exception using errcode = 'P0002', message = 'Lote de staging legado não encontrado.';
    end if;

    select count(*)::bigint,
           count(*) filter (where t.type = 'order')::bigint,
           count(*) filter (where t.type = 'payment')::bigint,
           count(*) filter (where t.type = 'signal')::bigint
      into v_source_transactions, v_source_orders, v_source_payments, v_source_signals
      from private.legacy_v1_transactions t
     where t.batch_id = p_batch_id;

    select count(*)::bigint into v_source_items
      from private.legacy_v1_items i where i.batch_id = p_batch_id;
    select count(*)::bigint into v_source_resellers
      from private.legacy_v1_resellers r where r.batch_id = p_batch_id;
    select count(distinct lower(c.category_name))::bigint into v_expected_categories
      from private.legacy_v1_item_classifications c where c.batch_id = p_batch_id;

    select count(*)::bigint into v_target_items from public.items;
    select count(*)::bigint into v_target_resellers from public.resellers;
    select count(*)::bigint,
           count(*) filter (where t.type = 'order')::bigint,
           count(*) filter (where t.type = 'payment')::bigint,
           count(*) filter (where t.type = 'signal')::bigint
      into v_target_transactions, v_target_orders, v_target_payments, v_target_signals
      from public.transactions t;
    select count(*)::bigint into v_target_categories from public.categories;

    select
        not exists (
            (
                select
                    s.id, s.name, s.base_price_cents, s.is_active, c.category_name,
                    s.created_at, s.updated_at
                from private.legacy_v1_items s
                join private.legacy_v1_item_classifications c
                  on c.batch_id = s.batch_id and c.item_id = s.id
                where s.batch_id = p_batch_id
            )
            except
            (
                select
                    p.id, p.name, (p.base_price * 100)::bigint, p.is_active, c.name,
                    p.created_at, p.updated_at
                from public.items p
                join public.categories c on c.id = p.category_id
            )
        )
        and not exists (
            (
                select
                    p.id, p.name, (p.base_price * 100)::bigint, p.is_active, c.name,
                    p.created_at, p.updated_at
                from public.items p
                join public.categories c on c.id = p.category_id
            )
            except
            (
                select
                    s.id, s.name, s.base_price_cents, s.is_active, c.category_name,
                    s.created_at, s.updated_at
                from private.legacy_v1_items s
                join private.legacy_v1_item_classifications c
                  on c.batch_id = s.batch_id and c.item_id = s.id
                where s.batch_id = p_batch_id
            )
        )
      into v_items_match;

    select
        not exists (
            (
                select s.id, s.name, s.phone, s.email, s.notes, s.is_active, s.created_at, s.updated_at
                from private.legacy_v1_resellers s
                where s.batch_id = p_batch_id
            )
            except
            (
                select p.id, p.name, p.phone, p.email, p.notes, p.is_active, p.created_at, p.updated_at
                from public.resellers p
            )
        )
        and not exists (
            (
                select p.id, p.name, p.phone, p.email, p.notes, p.is_active, p.created_at, p.updated_at
                from public.resellers p
            )
            except
            (
                select s.id, s.name, s.phone, s.email, s.notes, s.is_active, s.created_at, s.updated_at
                from private.legacy_v1_resellers s
                where s.batch_id = p_batch_id
            )
        )
      into v_resellers_match;

    select
        not exists (
            (
                select
                    s.id, s.reseller_id, s.type, s.item_id, s.item_name, s.quantity,
                    s.unit_price_cents, s.total_price_cents, s.observation,
                    s.category_id, s.category_name, s.reversal_reason, s.reversed_at,
                    s.replacement_transaction_id, s.replaces_transaction_id,
                    s.occurred_at, s.created_at
                from private.legacy_v1_transactions s
                where s.batch_id = p_batch_id
            )
            except
            (
                select
                    p.id, p.reseller_id, p.type, p.item_id, p.item_name, p.quantity,
                    case when p.unit_price is null then null else (p.unit_price * 100)::bigint end,
                    (p.total_price * 100)::bigint, p.observation,
                    p.category_id, p.category_name, p.reversal_reason, p.reversed_at,
                    p.replacement_transaction_id, p.replaces_transaction_id,
                    p.occurred_at, p.created_at
                from public.transactions p
            )
        )
        and not exists (
            (
                select
                    p.id, p.reseller_id, p.type, p.item_id, p.item_name, p.quantity,
                    case when p.unit_price is null then null else (p.unit_price * 100)::bigint end,
                    (p.total_price * 100)::bigint, p.observation,
                    p.category_id, p.category_name, p.reversal_reason, p.reversed_at,
                    p.replacement_transaction_id, p.replaces_transaction_id,
                    p.occurred_at, p.created_at
                from public.transactions p
            )
            except
            (
                select
                    s.id, s.reseller_id, s.type, s.item_id, s.item_name, s.quantity,
                    s.unit_price_cents, s.total_price_cents, s.observation,
                    s.category_id, s.category_name, s.reversal_reason, s.reversed_at,
                    s.replacement_transaction_id, s.replaces_transaction_id,
                    s.occurred_at, s.created_at
                from private.legacy_v1_transactions s
                where s.batch_id = p_batch_id
            )
        )
      into v_transactions_match;

    select
        v_target_categories = v_expected_categories
        and not exists (
            select 1
              from public.categories c
             where not exists (
                select 1
                  from private.legacy_v1_item_classifications sc
                 where sc.batch_id = p_batch_id
                   and lower(sc.category_name) = lower(c.name)
                   and sc.category_name = c.name
             )
        )
      into v_categories_match;

    select
        not exists (
            select 1
              from public.transactions t
              left join public.resellers r on r.id = t.reseller_id
             where r.id is null
        )
        and not exists (
            select 1
              from public.transactions t
              left join public.items i on i.id = t.item_id
             where t.type = 'order' and i.id is null
        )
      into v_references_match;

    select not exists (
        select 1
          from public.transactions t
         where t.category_id is not null
            or t.category_name is not null
            or t.reversal_reason is not null
            or t.reversed_at is not null
            or t.replacement_transaction_id is not null
            or t.replaces_transaction_id is not null
    ) into v_history_clean;

    v_sequences_ahead :=
        private.identity_sequence_is_ahead('public.categories'::regclass, 'id')
        and private.identity_sequence_is_ahead('public.items'::regclass, 'id')
        and private.identity_sequence_is_ahead('public.resellers'::regclass, 'id')
        and private.identity_sequence_is_ahead('public.transactions'::regclass, 'id');

    select
        coalesce(sum(t.total_price_cents) filter (where t.type = 'order'), 0)::bigint,
        coalesce(sum(t.total_price_cents) filter (where t.type = 'payment'), 0)::bigint,
        coalesce(sum(t.total_price_cents) filter (where t.type = 'signal'), 0)::bigint,
        coalesce(sum(case when t.type = 'order' then t.total_price_cents else -t.total_price_cents end), 0)::bigint
      into v_source_gross, v_source_payments_value, v_source_signals_value, v_source_net
      from private.legacy_v1_transactions t
     where t.batch_id = p_batch_id;

    select
        coalesce(sum((t.total_price * 100)::bigint) filter (where t.type = 'order'), 0)::bigint,
        coalesce(sum((t.total_price * 100)::bigint) filter (where t.type = 'payment'), 0)::bigint,
        coalesce(sum((t.total_price * 100)::bigint) filter (where t.type = 'signal'), 0)::bigint,
        coalesce(sum(case when t.type = 'order' then (t.total_price * 100)::bigint else -(t.total_price * 100)::bigint end), 0)::bigint
      into v_target_gross, v_target_payments_value, v_target_signals_value, v_target_net
      from public.transactions t;

    with source_balances as (
        select
            r.id as reseller_id,
            coalesce(sum(case when t.type = 'order' then t.total_price_cents else -t.total_price_cents end), 0)::bigint as balance_cents
        from private.legacy_v1_resellers r
        left join private.legacy_v1_transactions t
          on t.batch_id = r.batch_id and t.reseller_id = r.id
        where r.batch_id = p_batch_id
        group by r.id
    ),
    target_balances as (
        select
            r.id as reseller_id,
            coalesce(sum(case when t.type = 'order' then (t.total_price * 100)::bigint else -(t.total_price * 100)::bigint end), 0)::bigint as balance_cents
        from public.resellers r
        left join public.transactions t on t.reseller_id = r.id
        group by r.id
    )
    select
        not exists (
            select 1
              from source_balances s
              full join target_balances t using (reseller_id)
             where coalesce(s.balance_cents, 0) <> coalesce(t.balance_cents, 0)
                or s.reseller_id is null
                or t.reseller_id is null
        ),
        coalesce((select sum(greatest(balance_cents, 0))::bigint from source_balances), 0),
        coalesce((select sum(greatest(balance_cents, 0))::bigint from target_balances), 0)
      into v_balances_match, v_source_positive_debt, v_target_positive_debt;

    v_financial_match :=
        v_source_gross = v_target_gross
        and v_source_payments_value = v_target_payments_value
        and v_source_signals_value = v_target_signals_value
        and v_source_net = v_target_net
        and v_source_positive_debt = v_target_positive_debt
        and v_balances_match;

    v_passed :=
        v_source_items = v_target_items
        and v_source_resellers = v_target_resellers
        and v_source_transactions = v_target_transactions
        and v_source_orders = v_target_orders
        and v_source_payments = v_target_payments
        and v_source_signals = v_target_signals
        and v_items_match
        and v_resellers_match
        and v_transactions_match
        and v_categories_match
        and v_references_match
        and v_history_clean
        and v_sequences_ahead
        and v_financial_match;

    return pg_catalog.jsonb_build_object(
        'passed', v_passed,
        'counts', pg_catalog.jsonb_build_object(
            'items', v_target_items,
            'resellers', v_target_resellers,
            'transactions', v_target_transactions,
            'orders', v_target_orders,
            'payments', v_target_payments,
            'signals', v_target_signals,
            'categories', v_target_categories
        ),
        'checks', pg_catalog.jsonb_build_object(
            'itemsExact', v_items_match,
            'resellersExact', v_resellers_match,
            'transactionsExact', v_transactions_match,
            'categoriesExact', v_categories_match,
            'referencesExact', v_references_match,
            'legacyHistoryUnfabricated', v_history_clean,
            'sequencesAhead', v_sequences_ahead,
            'resellerBalancesExact', v_balances_match
        ),
        'financialCents', pg_catalog.jsonb_build_object(
            'grossOrders', v_target_gross,
            'payments', v_target_payments_value,
            'signals', v_target_signals_value,
            'netMovement', v_target_net,
            'positiveDebt', v_target_positive_debt
        )
    );
end;
$$;

create or replace function private.promote_legacy_v1_import(p_batch_id bigint)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_batch private.legacy_v1_import_batches%rowtype;
    v_result jsonb;
    v_promoted_at timestamptz := clock_timestamp();
    v_expected integer;
    v_actual integer;
begin
    select *
      into v_batch
      from private.legacy_v1_import_batches b
     where b.id = p_batch_id
     for update;

    if not found then
        raise exception using errcode = 'P0002', message = 'Lote de staging legado não encontrado.';
    end if;

    if v_batch.promoted_at is not null then
        raise exception using errcode = '23514', message = 'Lote de staging legado já foi promovido.';
    end if;

    if v_batch.classified_at is null then
        raise exception using errcode = '23514', message = 'Classificação atual explícita deve ser confirmada antes da promoção.';
    end if;

    lock table public.categories, public.items, public.resellers, public.transactions
        in access exclusive mode;

    if exists (select 1 from public.categories)
       or exists (select 1 from public.items)
       or exists (select 1 from public.resellers)
       or exists (select 1 from public.transactions)
    then
        raise exception using errcode = '55000', message = 'Promoção v1 exige tabelas públicas de negócio vazias.';
    end if;

    select count(*)::integer
      into v_expected
      from private.legacy_v1_items i
     where i.batch_id = p_batch_id and i.is_active;

    select count(*)::integer
      into v_actual
      from private.legacy_v1_item_classifications c
     where c.batch_id = p_batch_id;

    if v_actual <> v_expected then
        raise exception using errcode = '23514', message = 'Classificação atual explícita está incompleta.';
    end if;

    perform private.repair_identity_sequence('public.categories'::regclass, 'id');

    insert into public.categories(name, is_active, created_at, updated_at)
    select min(c.category_name), true, v_promoted_at, v_promoted_at
      from private.legacy_v1_item_classifications c
     where c.batch_id = p_batch_id
     group by lower(c.category_name)
     order by lower(min(c.category_name));

    insert into public.items(id, name, base_price, is_active, category_id, created_at, updated_at)
    select
        s.id,
        s.name,
        s.base_price_cents::numeric / 100,
        s.is_active,
        c.id,
        s.created_at,
        s.updated_at
      from private.legacy_v1_items s
      join private.legacy_v1_item_classifications sc
        on sc.batch_id = s.batch_id and sc.item_id = s.id
      join public.categories c
        on lower(c.name) = lower(sc.category_name)
       and c.name = sc.category_name
     where s.batch_id = p_batch_id
     order by s.id;

    insert into public.resellers(id, name, phone, email, notes, is_active, created_at, updated_at)
    select
        s.id, s.name, s.phone, s.email, s.notes, s.is_active, s.created_at, s.updated_at
      from private.legacy_v1_resellers s
     where s.batch_id = p_batch_id
     order by s.id;

    insert into public.transactions(
        id, reseller_id, type, item_id, item_name, quantity, unit_price,
        category_id, category_name, total_price, observation,
        reversal_reason, reversed_at, replacement_transaction_id, replaces_transaction_id,
        occurred_at, created_at
    )
    select
        s.id,
        s.reseller_id,
        s.type,
        s.item_id,
        s.item_name,
        s.quantity,
        case when s.unit_price_cents is null then null else s.unit_price_cents::numeric / 100 end,
        null,
        null,
        s.total_price_cents::numeric / 100,
        s.observation,
        null,
        null,
        null,
        null,
        s.occurred_at,
        s.created_at
      from private.legacy_v1_transactions s
     where s.batch_id = p_batch_id
     order by s.id;

    perform private.repair_identity_sequence('public.categories'::regclass, 'id');
    perform private.repair_identity_sequence('public.items'::regclass, 'id');
    perform private.repair_identity_sequence('public.resellers'::regclass, 'id');
    perform private.repair_identity_sequence('public.transactions'::regclass, 'id');

    v_result := private.reconcile_legacy_v1_import(p_batch_id);

    if coalesce((v_result ->> 'passed')::boolean, false) is not true then
        raise exception using errcode = '23514', message = 'Reconciliação exata falhou; promoção v1 revertida integralmente.';
    end if;

    update private.legacy_v1_import_batches
       set promoted_at = v_promoted_at
     where id = p_batch_id;

    return v_result || pg_catalog.jsonb_build_object('promoted', true);
end;
$$;

create or replace function private.discard_legacy_v1_import(p_batch_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
    delete from private.legacy_v1_import_batches b where b.id = p_batch_id;
    if not found then
        raise exception using errcode = 'P0002', message = 'Lote de staging legado não encontrado.';
    end if;
end;
$$;

revoke execute on function private.jsonb_has_exact_keys(jsonb, text[]) from public, anon, authenticated, service_role;
revoke execute on function private.stage_legacy_v1_normalized(jsonb) from public, anon, authenticated, service_role;
revoke execute on function private.set_legacy_v1_classifications(bigint, jsonb) from public, anon, authenticated, service_role;
revoke execute on function private.repair_identity_sequence(regclass, name) from public, anon, authenticated, service_role;
revoke execute on function private.identity_sequence_is_ahead(regclass, name) from public, anon, authenticated, service_role;
revoke execute on function private.reconcile_legacy_v1_import(bigint) from public, anon, authenticated, service_role;
revoke execute on function private.promote_legacy_v1_import(bigint) from public, anon, authenticated, service_role;
revoke execute on function private.discard_legacy_v1_import(bigint) from public, anon, authenticated, service_role;

comment on table private.legacy_v1_import_batches is
'Non-exposed D-030 stable-v1 import staging. Trusted database/admin tooling only; never browser Data API.';
comment on function private.stage_legacy_v1_normalized(jsonb) is
'Stages only the canonical normalized stable-v1 payload produced after Easy backup preflight. Not exposed to browser roles.';
comment on function private.promote_legacy_v1_import(bigint) is
'Atomically promotes a fully classified legacy-v1 staging batch into empty canonical public business tables and requires exact reconciliation.';
