create table private.recovery_backup_generations (
    id bigint generated by default as identity primary key,
    artifact_name text not null unique,
    sha256 text not null,
    byte_size bigint not null,
    offsite_verified_at timestamptz not null,
    retained_generation_count integer not null,
    recorded_at timestamptz not null default clock_timestamp(),
    constraint recovery_backup_artifact_name_not_blank check (btrim(artifact_name) <> ''),
    constraint recovery_backup_sha256_valid check (sha256 ~ '^[0-9a-f]{64}$'),
    constraint recovery_backup_byte_size_positive check (byte_size > 0),
    constraint recovery_backup_retention_minimum check (retained_generation_count >= 7)
);

alter table private.recovery_backup_generations enable row level security;

revoke all on table private.recovery_backup_generations from public, anon, authenticated, service_role;
revoke all on sequence private.recovery_backup_generations_id_seq from public, anon, authenticated, service_role;

create or replace function private.is_direct_database_maintenance()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
    select
        (
            current_user = 'postgres'
            or session_user = 'postgres'
            or pg_has_role(current_user, 'postgres', 'member')
            or pg_has_role(session_user, 'postgres', 'member')
        )
        and nullif(current_setting('request.jwt.claim.role', true), '') is null
        and nullif(current_setting('request.jwt.claim.sub', true), '') is null
        and nullif(current_setting('request.jwt.claims', true), '') is null;
$$;

create or replace function private.record_recovery_backup_success(
    p_artifact_name text,
    p_sha256 text,
    p_byte_size bigint,
    p_offsite_verified_at timestamptz,
    p_retained_generation_count integer
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_id bigint;
begin
    if not private.is_direct_database_maintenance() then
        raise exception using
            errcode = '42501',
            message = 'Recovery backup success may only be recorded from the trusted direct database maintenance boundary.';
    end if;

    if p_offsite_verified_at is null
       or p_offsite_verified_at > clock_timestamp() + interval '5 minutes'
    then
        raise exception using
            errcode = '22023',
            message = 'Invalid off-site verification timestamp.';
    end if;

    insert into private.recovery_backup_generations (
        artifact_name,
        sha256,
        byte_size,
        offsite_verified_at,
        retained_generation_count
    )
    values (
        btrim(p_artifact_name),
        lower(btrim(p_sha256)),
        p_byte_size,
        p_offsite_verified_at,
        p_retained_generation_count
    )
    returning id into v_id;

    return v_id;
end;
$$;

create or replace function private.latest_recovery_backup_success_at()
returns timestamptz
language sql
stable
security invoker
set search_path = ''
as $$
    select max(r.offsite_verified_at)
      from private.recovery_backup_generations r;
$$;

create or replace function private.recovery_backup_is_fresh_at(p_now timestamptz)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
    select coalesce(
        p_now <= private.latest_recovery_backup_success_at() + interval '24 hours',
        false
    );
$$;

create or replace function private.assert_recovery_backup_fresh()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_latest timestamptz;
begin
    if private.is_direct_database_maintenance() then
        return;
    end if;

    v_latest := private.latest_recovery_backup_success_at();

    if v_latest is null or clock_timestamp() > v_latest + interval '24 hours' then
        raise exception using
            errcode = '55000',
            message = 'Business writes are blocked because the latest verified off-site backup is missing or older than 24 hours.';
    end if;
end;
$$;

create or replace function private.guard_business_write_recovery_health()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    perform private.assert_recovery_backup_fresh();
    return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create trigger categories_require_fresh_recovery_backup
before insert or update or delete on public.categories
for each row execute function private.guard_business_write_recovery_health();

create trigger items_require_fresh_recovery_backup
before insert or update or delete on public.items
for each row execute function private.guard_business_write_recovery_health();

create trigger resellers_require_fresh_recovery_backup
before insert or update or delete on public.resellers
for each row execute function private.guard_business_write_recovery_health();

create trigger transactions_require_fresh_recovery_backup
before insert or update or delete on public.transactions
for each row execute function private.guard_business_write_recovery_health();

revoke all on function private.is_direct_database_maintenance() from public, anon, authenticated, service_role;
revoke all on function private.record_recovery_backup_success(text, text, bigint, timestamptz, integer) from public, anon, authenticated, service_role;
revoke all on function private.latest_recovery_backup_success_at() from public, anon, authenticated, service_role;
revoke all on function private.recovery_backup_is_fresh_at(timestamptz) from public, anon, authenticated, service_role;
revoke all on function private.assert_recovery_backup_fresh() from public, anon, authenticated, service_role;
revoke all on function private.guard_business_write_recovery_health() from public, anon, authenticated, service_role;

comment on table private.recovery_backup_generations is 'Sanitized evidence for objectively verified off-site logical backup generations. Excluded from business-data dumps and writable only through trusted direct database maintenance.';
comment on function private.recovery_backup_is_fresh_at(timestamptz) is 'D-030 exact 24-hour recovery freshness predicate: exactly 24h is fresh; any later instant is stale.';
comment on function private.assert_recovery_backup_fresh() is 'D-030 fail-closed guard for canonical business writes. Direct database maintenance without PostgREST JWT claims is the narrow restore/import bypass.';
