create table public.subcategories (
    id bigint generated by default as identity primary key,
    category_id bigint not null references public.categories(id) on update restrict on delete restrict,
    name text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint subcategories_name_not_blank check (btrim(name) <> ''),
    constraint subcategories_id_category_unique unique (id, category_id)
);

create unique index subcategories_category_normalized_name_unique
    on public.subcategories (category_id, (lower(btrim(name))));
create index subcategories_category_id_idx on public.subcategories(category_id);

create trigger subcategories_touch_updated_at
before update on public.subcategories
for each row execute function private.touch_updated_at();

alter table public.subcategories enable row level security;

create policy subcategories_operator_select
on public.subcategories
for select
to authenticated
using ((select public.is_easy_operator()));

create policy subcategories_operator_insert
on public.subcategories
for insert
to authenticated
with check ((select public.is_easy_operator()));

create policy subcategories_operator_update
on public.subcategories
for update
to authenticated
using ((select public.is_easy_operator()))
with check ((select public.is_easy_operator()));

create policy subcategories_operator_delete
on public.subcategories
for delete
to authenticated
using ((select public.is_easy_operator()));

revoke all on table public.subcategories from public, anon, authenticated;
grant select, insert, update, delete on table public.subcategories to authenticated;
grant usage, select on sequence public.subcategories_id_seq to authenticated;

create trigger subcategories_require_fresh_recovery_backup
before insert or update or delete on public.subcategories
for each row execute function private.guard_business_write_recovery_health();

alter table public.items add column subcategory_id bigint null;
alter table public.items
    add constraint items_subcategory_category_fk
    foreign key (subcategory_id, category_id)
    references public.subcategories(id, category_id)
    on update restrict on delete restrict;
create index items_subcategory_id_idx on public.items(subcategory_id);

alter table public.transactions add column subcategory_id bigint null;
alter table public.transactions add column subcategory_name text null;
alter table public.transactions
    add constraint transactions_subcategory_id_fkey
    foreign key (subcategory_id)
    references public.subcategories(id)
    on update restrict on delete restrict;
create index transactions_subcategory_id_idx on public.transactions(subcategory_id);

alter table public.transactions
    add constraint transactions_subcategory_shape_valid check (
        (
            type = 'order'
            and (
                (subcategory_id is null and subcategory_name is null)
                or (
                    subcategory_id is not null
                    and subcategory_name is not null
                    and btrim(subcategory_name) <> ''
                    and category_id is not null
                    and category_name is not null
                )
            )
        )
        or
        (
            type in ('payment', 'signal')
            and subcategory_id is null
            and subcategory_name is null
        )
    );

create or replace function private.validate_subcategory_category()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_category_active boolean;
begin
    select c.is_active
      into v_category_active
      from public.categories c
     where c.id = new.category_id;

    if not found then
        raise exception using
            errcode = '23503',
            message = 'A categoria da subcategoria não existe.';
    end if;

    if new.is_active and v_category_active is not true then
        raise exception using
            errcode = '23514',
            message = 'Subcategorias ativas devem pertencer a uma categoria ativa.';
    end if;

    return new;
end;
$$;

create trigger subcategories_validate_category
before insert or update on public.subcategories
for each row execute function private.validate_subcategory_category();

create or replace function private.validate_item_subcategory()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_subcategory_active boolean;
begin
    if new.subcategory_id is null then
        return new;
    end if;

    select s.is_active
      into v_subcategory_active
      from public.subcategories s
     where s.id = new.subcategory_id
       and s.category_id = new.category_id;

    if not found then
        raise exception using
            errcode = '23514',
            message = 'A subcategoria selecionada deve pertencer à categoria do item.';
    end if;

    if new.is_active and v_subcategory_active is not true then
        raise exception using
            errcode = '23514',
            message = 'Itens ativos não podem usar uma subcategoria arquivada.';
    end if;

    return new;
end;
$$;

create trigger items_validate_subcategory
before insert or update on public.items
for each row execute function private.validate_item_subcategory();

create or replace function private.guard_subcategory_archive()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    if old.is_active and not new.is_active
       and exists (
            select 1
              from public.items i
             where i.subcategory_id = old.id
               and i.is_active
       )
    then
        raise exception using
            errcode = '23514',
            message = 'Subcategorias usadas por itens ativos não podem ser arquivadas.';
    end if;

    return new;
end;
$$;

create trigger subcategories_guard_archive
before update of is_active on public.subcategories
for each row execute function private.guard_subcategory_archive();

create or replace function private.guard_category_archive()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    if old.is_active and not new.is_active
       and (
            exists (
                select 1
                  from public.items i
                 where i.category_id = old.id
                   and i.is_active
            )
            or exists (
                select 1
                  from public.subcategories s
                 where s.category_id = old.id
                   and s.is_active
            )
       )
    then
        raise exception using
            errcode = '23514',
            message = 'Categorias com itens ou subcategorias ativos não podem ser arquivadas.';
    end if;

    return new;
end;
$$;

create or replace function public.create_transaction(
    p_reseller_id bigint,
    p_type text,
    p_occurred_at timestamptz default null,
    p_observation text default null,
    p_item_id bigint default null,
    p_quantity integer default null,
    p_unit_price numeric default null,
    p_total_price numeric default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_transaction_id bigint;
    v_created_at timestamptz := clock_timestamp();
    v_occurred_at timestamptz := coalesce(p_occurred_at, v_created_at);
    v_item_name text;
    v_category_id bigint;
    v_category_name text;
    v_subcategory_id bigint;
    v_subcategory_name text;
    v_total numeric;
begin
    perform private.assert_easy_operator();

    if p_type not in ('order', 'payment', 'signal') then
        raise exception using errcode = '22023', message = 'Tipo de movimentação inválido.';
    end if;

    if not exists (
        select 1 from public.resellers r
         where r.id = p_reseller_id
           and r.is_active
    ) then
        raise exception using errcode = '23503', message = 'Revendedor inexistente ou inativo.';
    end if;

    if p_type = 'order' then
        if p_item_id is null or p_quantity is null or p_quantity <= 0
           or p_unit_price is null or p_unit_price < 0
        then
            raise exception using errcode = '22023', message = 'Pedido requer item, quantidade positiva e preço unitário não negativo.';
        end if;

        if p_total_price is not null then
            raise exception using errcode = '22023', message = 'O total do pedido é calculado pelo servidor.';
        end if;

        select i.name, i.category_id, c.name, i.subcategory_id, s.name
          into v_item_name, v_category_id, v_category_name, v_subcategory_id, v_subcategory_name
          from public.items i
          join public.categories c on c.id = i.category_id
          left join public.subcategories s
            on s.id = i.subcategory_id
           and s.category_id = i.category_id
         where i.id = p_item_id
           and i.is_active
           and c.is_active
           and (i.subcategory_id is null or s.is_active);

        if not found then
            raise exception using errcode = '23503', message = 'Item inexistente, inativo ou com classificação inativa.';
        end if;

        v_total := p_quantity * p_unit_price;

        insert into public.transactions (
            reseller_id, type, item_id, item_name, quantity, unit_price,
            category_id, category_name, subcategory_id, subcategory_name,
            total_price, observation, occurred_at, created_at
        )
        values (
            p_reseller_id, p_type, p_item_id, v_item_name, p_quantity, p_unit_price,
            v_category_id, v_category_name, v_subcategory_id, v_subcategory_name,
            v_total, p_observation, v_occurred_at, v_created_at
        )
        returning id into v_transaction_id;
    else
        if p_item_id is not null or p_quantity is not null or p_unit_price is not null then
            raise exception using errcode = '22023', message = 'Pagamentos e sinais não podem carregar campos de pedido.';
        end if;

        if p_total_price is null or p_total_price <= 0 then
            raise exception using errcode = '22023', message = 'Pagamento ou sinal requer valor positivo.';
        end if;

        insert into public.transactions (
            reseller_id, type, total_price, observation, occurred_at, created_at
        )
        values (
            p_reseller_id, p_type, p_total_price, p_observation, v_occurred_at, v_created_at
        )
        returning id into v_transaction_id;
    end if;

    return v_transaction_id;
end;
$$;

create or replace function public.correct_transaction(
    p_original_id bigint,
    p_reason text,
    p_reseller_id bigint,
    p_type text,
    p_occurred_at timestamptz,
    p_observation text default null,
    p_item_id bigint default null,
    p_quantity integer default null,
    p_unit_price numeric default null,
    p_total_price numeric default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_original public.transactions%rowtype;
    v_replacement_id bigint;
    v_created_at timestamptz := clock_timestamp();
    v_item_name text;
    v_category_id bigint;
    v_category_name text;
    v_subcategory_id bigint;
    v_subcategory_name text;
    v_total numeric;
begin
    perform private.assert_easy_operator();

    if btrim(coalesce(p_reason, '')) = '' then
        raise exception using errcode = '22023', message = 'Informe o motivo da correção.';
    end if;

    if p_type not in ('order', 'payment', 'signal') then
        raise exception using errcode = '22023', message = 'Tipo de movimentação inválido.';
    end if;

    if p_occurred_at is null then
        raise exception using errcode = '22023', message = 'Informe uma data de ocorrência válida.';
    end if;

    select t.*
      into v_original
      from public.transactions t
     where t.id = p_original_id
     for update;

    if not found then
        raise exception using errcode = 'P0002', message = 'Lançamento não encontrado.';
    end if;

    if v_original.reversed_at is not null then
        raise exception using errcode = '23514', message = 'Este lançamento já foi estornado.';
    end if;

    if not exists (
        select 1 from public.resellers r
         where r.id = p_reseller_id
           and r.is_active
    ) then
        raise exception using errcode = '23503', message = 'Revendedor inexistente ou inativo.';
    end if;

    if p_type = 'order' then
        if p_item_id is null or p_quantity is null or p_quantity <= 0
           or p_unit_price is null or p_unit_price < 0
        then
            raise exception using errcode = '22023', message = 'Pedido corrigido requer item, quantidade positiva e preço unitário não negativo.';
        end if;

        if p_total_price is not null then
            raise exception using errcode = '22023', message = 'O total do pedido corrigido é calculado pelo servidor.';
        end if;

        if v_original.type = 'order' and v_original.item_id = p_item_id then
            if not exists (
                select 1 from public.items i
                 where i.id = p_item_id
                   and i.is_active
            ) then
                raise exception using errcode = '23503', message = 'Item inexistente ou inativo.';
            end if;

            v_item_name := v_original.item_name;
            v_category_id := v_original.category_id;
            v_category_name := v_original.category_name;
            v_subcategory_id := v_original.subcategory_id;
            v_subcategory_name := v_original.subcategory_name;
        else
            select i.name, i.category_id, c.name, i.subcategory_id, s.name
              into v_item_name, v_category_id, v_category_name, v_subcategory_id, v_subcategory_name
              from public.items i
              join public.categories c on c.id = i.category_id
              left join public.subcategories s
                on s.id = i.subcategory_id
               and s.category_id = i.category_id
             where i.id = p_item_id
               and i.is_active
               and c.is_active
               and (i.subcategory_id is null or s.is_active);

            if not found then
                raise exception using errcode = '23503', message = 'Item inexistente, inativo ou com classificação inativa.';
            end if;
        end if;

        v_total := p_quantity * p_unit_price;

        insert into public.transactions (
            reseller_id, type, item_id, item_name, quantity, unit_price,
            category_id, category_name, subcategory_id, subcategory_name,
            total_price, observation, replaces_transaction_id, occurred_at, created_at
        )
        values (
            p_reseller_id, p_type, p_item_id, v_item_name, p_quantity, p_unit_price,
            v_category_id, v_category_name, v_subcategory_id, v_subcategory_name,
            v_total, p_observation, p_original_id, p_occurred_at, v_created_at
        )
        returning id into v_replacement_id;
    else
        if p_item_id is not null or p_quantity is not null or p_unit_price is not null then
            raise exception using errcode = '22023', message = 'Pagamentos e sinais corrigidos não podem carregar campos de pedido.';
        end if;

        if p_total_price is null or p_total_price <= 0 then
            raise exception using errcode = '22023', message = 'Pagamento ou sinal corrigido requer valor positivo.';
        end if;

        insert into public.transactions (
            reseller_id, type, total_price, observation,
            replaces_transaction_id, occurred_at, created_at
        )
        values (
            p_reseller_id, p_type, p_total_price, p_observation,
            p_original_id, p_occurred_at, v_created_at
        )
        returning id into v_replacement_id;
    end if;

    update public.transactions
       set reversal_reason = btrim(p_reason),
           reversed_at = v_created_at,
           replacement_transaction_id = v_replacement_id
     where id = p_original_id;

    return v_replacement_id;
end;
$$;

create or replace function public.restore_easy_backup(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_schema_version text;
    v_categories jsonb;
    v_subcategories jsonb;
    v_items jsonb;
    v_resellers jsonb;
    v_transactions jsonb;
begin
    perform private.assert_easy_operator();

    v_schema_version := p_payload#>>'{source,schemaVersion}';

    if p_payload is null
       or jsonb_typeof(p_payload) <> 'object'
       or p_payload->>'format' <> 'easy-backup'
       or p_payload->>'version' <> '2'
       or p_payload#>>'{source,database}' <> 'ResellerManagerDB'
       or v_schema_version not in ('5', '6')
    then
        raise exception using
            errcode = '22023',
            message = 'A restauração em nuvem aceita somente Backup v2/schema5 ou schema6 validado.';
    end if;

    v_categories := p_payload#>'{data,categories}';
    v_subcategories := case
        when v_schema_version = '6' then p_payload#>'{data,subcategories}'
        else '[]'::jsonb
    end;
    v_items := p_payload#>'{data,items}';
    v_resellers := p_payload#>'{data,resellers}';
    v_transactions := p_payload#>'{data,transactions}';

    if jsonb_typeof(v_categories) <> 'array'
       or jsonb_typeof(v_subcategories) <> 'array'
       or jsonb_typeof(v_items) <> 'array'
       or jsonb_typeof(v_resellers) <> 'array'
       or jsonb_typeof(v_transactions) <> 'array'
    then
        raise exception using
            errcode = '22023',
            message = 'Backup sem as coleções obrigatórias para a versão informada.';
    end if;

    perform set_config('easy.authorized_logical_restore', 'on', true);
    set constraints transactions_replacement_transaction_fk, transactions_replaces_transaction_fk deferred;

    delete from public.transactions;
    delete from public.items;
    delete from public.resellers;
    delete from public.subcategories;
    delete from public.categories;

    insert into public.categories (id, name, is_active, created_at, updated_at)
    select x.id, x.name, x."isActive", x."createdAt"::timestamptz, x."updatedAt"::timestamptz
    from jsonb_to_recordset(v_categories) as x(
        id bigint, name text, "isActive" boolean, "createdAt" text, "updatedAt" text
    );

    insert into public.subcategories (id, category_id, name, is_active, created_at, updated_at)
    select x.id, x."categoryId", x.name, x."isActive", x."createdAt"::timestamptz, x."updatedAt"::timestamptz
    from jsonb_to_recordset(v_subcategories) as x(
        id bigint, "categoryId" bigint, name text, "isActive" boolean, "createdAt" text, "updatedAt" text
    );

    insert into public.resellers (id, name, phone, email, notes, is_active, created_at, updated_at)
    select x.id, x.name, x.phone, x.email, x.notes, x."isActive", x."createdAt"::timestamptz, x."updatedAt"::timestamptz
    from jsonb_to_recordset(v_resellers) as x(
        id bigint, name text, phone text, email text, notes text, "isActive" boolean, "createdAt" text, "updatedAt" text
    );

    insert into public.items (id, name, base_price, is_active, category_id, subcategory_id, created_at, updated_at)
    select x.id, x.name, x."basePrice", x."isActive", x."categoryId", x."subcategoryId", x."createdAt"::timestamptz, x."updatedAt"::timestamptz
    from jsonb_to_recordset(v_items) as x(
        id bigint, name text, "basePrice" numeric, "isActive" boolean, "categoryId" bigint, "subcategoryId" bigint, "createdAt" text, "updatedAt" text
    );

    insert into public.transactions (
        id, reseller_id, type, item_id, item_name, quantity, unit_price,
        category_id, category_name, subcategory_id, subcategory_name,
        total_price, observation, reversal_reason, reversed_at,
        replacement_transaction_id, replaces_transaction_id, occurred_at, created_at
    )
    select
        x.id, x."resellerId", x.type, x."itemId", x."itemName", x.quantity, x."unitPrice",
        x."categoryId", x."categoryName", x."subcategoryId", x."subcategoryName",
        x."totalPrice", x.observation,
        nullif(x.reversal->>'reason', ''),
        case when x.reversal ? 'reversedAt' then (x.reversal->>'reversedAt')::timestamptz else null end,
        case when x.reversal ? 'replacementTransactionId' then (x.reversal->>'replacementTransactionId')::bigint else null end,
        case when x.correction ? 'replacesTransactionId' then (x.correction->>'replacesTransactionId')::bigint else null end,
        x."occurredAt"::timestamptz, x."createdAt"::timestamptz
    from jsonb_to_recordset(v_transactions) as x(
        id bigint, "resellerId" bigint, type text, "itemId" bigint, "itemName" text,
        quantity integer, "unitPrice" numeric, "categoryId" bigint, "categoryName" text,
        "subcategoryId" bigint, "subcategoryName" text, "totalPrice" numeric,
        observation text, reversal jsonb, correction jsonb, "occurredAt" text, "createdAt" text
    );

    if exists (
        select 1
        from public.transactions original
        join public.transactions replacement on replacement.id = original.replacement_transaction_id
        where replacement.replaces_transaction_id is distinct from original.id
           or replacement.created_at < original.created_at
           or (
                original.type = 'order'
                and replacement.type = 'order'
                and replacement.item_id = original.item_id
                and (
                    replacement.category_id is distinct from original.category_id
                    or replacement.category_name is distinct from original.category_name
                    or replacement.subcategory_id is distinct from original.subcategory_id
                    or replacement.subcategory_name is distinct from original.subcategory_name
                )
           )
    ) then
        raise exception using errcode = '23514', message = 'Backup contém vínculo de correção/reversão inválido.';
    end if;

    if exists (
        select 1
        from public.transactions replacement
        left join public.transactions original on original.id = replacement.replaces_transaction_id
        where replacement.replaces_transaction_id is not null
          and (original.id is null or original.replacement_transaction_id is distinct from replacement.id)
    ) then
        raise exception using errcode = '23514', message = 'Backup contém correção sem vínculo bidirecional correspondente.';
    end if;

    perform setval(pg_get_serial_sequence('public.categories', 'id'), coalesce((select max(id) from public.categories), 1), exists(select 1 from public.categories));
    perform setval(pg_get_serial_sequence('public.subcategories', 'id'), coalesce((select max(id) from public.subcategories), 1), exists(select 1 from public.subcategories));
    perform setval(pg_get_serial_sequence('public.items', 'id'), coalesce((select max(id) from public.items), 1), exists(select 1 from public.items));
    perform setval(pg_get_serial_sequence('public.resellers', 'id'), coalesce((select max(id) from public.resellers), 1), exists(select 1 from public.resellers));
    perform setval(pg_get_serial_sequence('public.transactions', 'id'), coalesce((select max(id) from public.transactions), 1), exists(select 1 from public.transactions));

    perform set_config('easy.authorized_logical_restore', 'off', true);

    return jsonb_build_object(
        'categories', (select count(*) from public.categories),
        'subcategories', (select count(*) from public.subcategories),
        'items', (select count(*) from public.items),
        'resellers', (select count(*) from public.resellers),
        'transactions', (select count(*) from public.transactions)
    );
exception
    when others then
        perform set_config('easy.authorized_logical_restore', 'off', true);
        raise;
end;
$$;

revoke all on function private.validate_subcategory_category() from public, anon, authenticated, service_role;
revoke all on function private.validate_item_subcategory() from public, anon, authenticated, service_role;
revoke all on function private.guard_subcategory_archive() from public, anon, authenticated, service_role;

comment on table public.subcategories is 'Optional second-level classification under a category. Stable identity is preserved and order history snapshots name/id independently.';
comment on column public.items.subcategory_id is 'Optional current catalog subcategory. Must belong to item.category_id.';
comment on column public.transactions.subcategory_id is 'Optional immutable transaction-time subcategory identity snapshot for order rows.';
comment on column public.transactions.subcategory_name is 'Optional immutable transaction-time subcategory name snapshot for order rows.';
comment on function public.restore_easy_backup(jsonb) is 'Approved-operator atomic logical restore for validated easy-backup v2/schema5 or schema6. Schema5 has no subcategory state; schema6 preserves it.';
