create schema if not exists private;
revoke all on schema private from public;
revoke all on schema private from anon;
revoke all on schema private from authenticated;

create table public.easy_operators (
    user_id uuid primary key,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.categories (
    id bigint generated by default as identity primary key,
    name text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint categories_name_not_blank check (btrim(name) <> '')
);

create unique index categories_normalized_name_unique
    on public.categories ((lower(btrim(name))));

create table public.items (
    id bigint generated by default as identity primary key,
    name text not null,
    base_price numeric not null,
    is_active boolean not null default true,
    category_id bigint null references public.categories(id) on update restrict on delete restrict,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint items_name_not_blank check (btrim(name) <> ''),
    constraint items_base_price_nonnegative check (base_price >= 0),
    constraint items_active_requires_category check (not is_active or category_id is not null)
);

create index items_category_id_idx on public.items(category_id);

create table public.resellers (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text null,
    email text null,
    notes text null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint resellers_name_not_blank check (btrim(name) <> '')
);

create table public.transactions (
    id bigint generated by default as identity primary key,
    reseller_id bigint not null references public.resellers(id) on update restrict on delete restrict,
    type text not null,
    item_id bigint null references public.items(id) on update restrict on delete restrict,
    item_name text null,
    quantity integer null,
    unit_price numeric null,
    category_id bigint null references public.categories(id) on update restrict on delete restrict,
    category_name text null,
    total_price numeric not null,
    observation text null,
    reversal_reason text null,
    reversed_at timestamptz null,
    replacement_transaction_id bigint null,
    replaces_transaction_id bigint null,
    occurred_at timestamptz not null,
    created_at timestamptz not null default now(),
    constraint transactions_type_valid check (type in ('order', 'payment', 'signal')),
    constraint transactions_order_shape_valid check (
        (
            type = 'order'
            and item_id is not null
            and item_name is not null
            and btrim(item_name) <> ''
            and quantity is not null
            and quantity > 0
            and unit_price is not null
            and unit_price >= 0
            and total_price = quantity * unit_price
            and (
                (category_id is null and category_name is null)
                or (category_id is not null and category_name is not null and btrim(category_name) <> '')
            )
        )
        or
        (
            type in ('payment', 'signal')
            and item_id is null
            and item_name is null
            and quantity is null
            and unit_price is null
            and category_id is null
            and category_name is null
            and total_price > 0
        )
    ),
    constraint transactions_reversal_shape_valid check (
        (
            reversal_reason is null
            and reversed_at is null
            and replacement_transaction_id is null
        )
        or
        (
            reversal_reason is not null
            and btrim(reversal_reason) <> ''
            and reversed_at is not null
        )
    ),
    constraint transactions_replacement_not_self check (
        replacement_transaction_id is null or replacement_transaction_id <> id
    ),
    constraint transactions_replaces_not_self check (
        replaces_transaction_id is null or replaces_transaction_id <> id
    ),
    constraint transactions_replacement_transaction_unique unique (replacement_transaction_id),
    constraint transactions_replaces_transaction_unique unique (replaces_transaction_id)
);

alter table public.transactions
    add constraint transactions_replacement_transaction_fk
    foreign key (replacement_transaction_id)
    references public.transactions(id)
    on update restrict on delete restrict
    deferrable initially immediate;

alter table public.transactions
    add constraint transactions_replaces_transaction_fk
    foreign key (replaces_transaction_id)
    references public.transactions(id)
    on update restrict on delete restrict
    deferrable initially immediate;

create index transactions_reseller_id_idx on public.transactions(reseller_id);
create index transactions_item_id_idx on public.transactions(item_id);
create index transactions_category_id_idx on public.transactions(category_id);
create index transactions_occurred_at_idx on public.transactions(occurred_at);
create index transactions_created_at_idx on public.transactions(created_at);
create index transactions_type_idx on public.transactions(type);

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    new.updated_at := clock_timestamp();
    return new;
end;
$$;

create trigger easy_operators_touch_updated_at
before update on public.easy_operators
for each row execute function private.touch_updated_at();

create trigger categories_touch_updated_at
before update on public.categories
for each row execute function private.touch_updated_at();

create trigger items_touch_updated_at
before update on public.items
for each row execute function private.touch_updated_at();

create trigger resellers_touch_updated_at
before update on public.resellers
for each row execute function private.touch_updated_at();

create or replace function private.validate_item_category()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_category_active boolean;
    v_must_validate boolean := false;
begin
    if new.is_active and new.category_id is null then
        raise exception using
            errcode = '23514',
            message = 'Itens ativos devem possuir uma categoria ativa.';
    end if;

    if new.category_id is not null then
        if tg_op = 'INSERT' then
            v_must_validate := true;
        elsif old.category_id is distinct from new.category_id
           or (not old.is_active and new.is_active)
        then
            v_must_validate := true;
        end if;
    end if;

    if v_must_validate then
        select c.is_active
          into v_category_active
          from public.categories c
         where c.id = new.category_id;

        if not found or v_category_active is not true then
            raise exception using
                errcode = '23514',
                message = 'A categoria selecionada deve existir e estar ativa.';
        end if;
    end if;

    return new;
end;
$$;

create trigger items_validate_category
before insert or update on public.items
for each row execute function private.validate_item_category();

create or replace function private.guard_category_archive()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    if old.is_active and not new.is_active
       and exists (
            select 1
              from public.items i
             where i.category_id = old.id
               and i.is_active
       )
    then
        raise exception using
            errcode = '23514',
            message = 'Categorias usadas por itens ativos não podem ser arquivadas.';
    end if;

    return new;
end;
$$;

create trigger categories_guard_archive
before update of is_active on public.categories
for each row execute function private.guard_category_archive();

create or replace function public.is_easy_operator()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
    select
        (select auth.uid()) is not null
        and exists (
            select 1
              from public.easy_operators eo
             where eo.user_id = (select auth.uid())
               and eo.is_active
        );
$$;

create or replace function private.assert_easy_operator()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
    if (select auth.uid()) is null
       or not exists (
            select 1
              from public.easy_operators eo
             where eo.user_id = (select auth.uid())
               and eo.is_active
       )
    then
        raise exception using
            errcode = '42501',
            message = 'Usuário não autorizado para operar o Easy.';
    end if;
end;
$$;

alter table public.easy_operators enable row level security;
alter table public.categories enable row level security;
alter table public.items enable row level security;
alter table public.resellers enable row level security;
alter table public.transactions enable row level security;

create policy easy_operators_select_self
on public.easy_operators
for select
to authenticated
using (
    (select auth.uid()) is not null
    and user_id = (select auth.uid())
);

create policy categories_operator_select
on public.categories
for select
to authenticated
using ((select public.is_easy_operator()));

create policy categories_operator_insert
on public.categories
for insert
to authenticated
with check ((select public.is_easy_operator()));

create policy categories_operator_update
on public.categories
for update
to authenticated
using ((select public.is_easy_operator()))
with check ((select public.is_easy_operator()));

create policy categories_operator_delete
on public.categories
for delete
to authenticated
using ((select public.is_easy_operator()));

create policy items_operator_select
on public.items
for select
to authenticated
using ((select public.is_easy_operator()));

create policy items_operator_insert
on public.items
for insert
to authenticated
with check ((select public.is_easy_operator()));

create policy items_operator_update
on public.items
for update
to authenticated
using ((select public.is_easy_operator()))
with check ((select public.is_easy_operator()));

create policy items_operator_delete
on public.items
for delete
to authenticated
using ((select public.is_easy_operator()));

create policy resellers_operator_select
on public.resellers
for select
to authenticated
using ((select public.is_easy_operator()));

create policy resellers_operator_insert
on public.resellers
for insert
to authenticated
with check ((select public.is_easy_operator()));

create policy resellers_operator_update
on public.resellers
for update
to authenticated
using ((select public.is_easy_operator()))
with check ((select public.is_easy_operator()));

create policy resellers_operator_delete
on public.resellers
for delete
to authenticated
using ((select public.is_easy_operator()));

create policy transactions_operator_select
on public.transactions
for select
to authenticated
using ((select public.is_easy_operator()));

revoke all on table public.easy_operators from anon, authenticated;
revoke all on table public.categories from anon, authenticated;
revoke all on table public.items from anon, authenticated;
revoke all on table public.resellers from anon, authenticated;
revoke all on table public.transactions from anon, authenticated;

grant select on table public.easy_operators to authenticated;
grant select, insert, update, delete on table public.categories to authenticated;
grant select, insert, update, delete on table public.items to authenticated;
grant select, insert, update, delete on table public.resellers to authenticated;
grant select on table public.transactions to authenticated;

grant usage, select on sequence public.categories_id_seq to authenticated;
grant usage, select on sequence public.items_id_seq to authenticated;
grant usage, select on sequence public.resellers_id_seq to authenticated;

revoke all on function public.is_easy_operator() from public, anon;
grant execute on function public.is_easy_operator() to authenticated;

create or replace function public.create_transaction(
    p_reseller_id bigint,
    p_type text,
    p_occurred_at timestamptz default null,
    p_observation text default null,
    p_item_id bigint default null,
    p_quantity integer default null,
    p_unit_price numeric default null,
    p_total_price numeric default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_transaction_id bigint;
    v_created_at timestamptz := clock_timestamp();
    v_occurred_at timestamptz := coalesce(p_occurred_at, v_created_at);
    v_item_name text;
    v_category_id bigint;
    v_category_name text;
    v_total numeric;
begin
    perform private.assert_easy_operator();

    if p_type not in ('order', 'payment', 'signal') then
        raise exception using errcode = '22023', message = 'Tipo de movimentação inválido.';
    end if;

    if not exists (
        select 1 from public.resellers r
         where r.id = p_reseller_id
           and r.is_active
    ) then
        raise exception using errcode = '23503', message = 'Revendedor inexistente ou inativo.';
    end if;

    if p_type = 'order' then
        if p_item_id is null or p_quantity is null or p_quantity <= 0
           or p_unit_price is null or p_unit_price < 0
        then
            raise exception using errcode = '22023', message = 'Pedido requer item, quantidade positiva e preço unitário não negativo.';
        end if;

        if p_total_price is not null then
            raise exception using errcode = '22023', message = 'O total do pedido é calculado pelo servidor.';
        end if;

        select i.name, i.category_id, c.name
          into v_item_name, v_category_id, v_category_name
          from public.items i
          join public.categories c on c.id = i.category_id
         where i.id = p_item_id
           and i.is_active
           and c.is_active;

        if not found then
            raise exception using errcode = '23503', message = 'Item inexistente, inativo ou sem categoria ativa.';
        end if;

        v_total := p_quantity * p_unit_price;

        insert into public.transactions (
            reseller_id, type, item_id, item_name, quantity, unit_price,
            category_id, category_name, total_price, observation, occurred_at, created_at
        )
        values (
            p_reseller_id, p_type, p_item_id, v_item_name, p_quantity, p_unit_price,
            v_category_id, v_category_name, v_total, p_observation, v_occurred_at, v_created_at
        )
        returning id into v_transaction_id;
    else
        if p_item_id is not null or p_quantity is not null or p_unit_price is not null then
            raise exception using errcode = '22023', message = 'Pagamentos e sinais não podem carregar campos de pedido.';
        end if;

        if p_total_price is null or p_total_price <= 0 then
            raise exception using errcode = '22023', message = 'Pagamento ou sinal requer valor positivo.';
        end if;

        insert into public.transactions (
            reseller_id, type, total_price, observation, occurred_at, created_at
        )
        values (
            p_reseller_id, p_type, p_total_price, p_observation, v_occurred_at, v_created_at
        )
        returning id into v_transaction_id;
    end if;

    return v_transaction_id;
end;
$$;

create or replace function public.reverse_transaction(
    p_transaction_id bigint,
    p_reason text
)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_reversed_at timestamptz := clock_timestamp();
    v_existing_reversed_at timestamptz;
begin
    perform private.assert_easy_operator();

    if btrim(coalesce(p_reason, '')) = '' then
        raise exception using errcode = '22023', message = 'Informe o motivo do estorno.';
    end if;

    select t.reversed_at
      into v_existing_reversed_at
      from public.transactions t
     where t.id = p_transaction_id
     for update;

    if not found then
        raise exception using errcode = 'P0002', message = 'Lançamento não encontrado.';
    end if;

    if v_existing_reversed_at is not null then
        raise exception using errcode = '23514', message = 'Este lançamento já foi estornado.';
    end if;

    update public.transactions
       set reversal_reason = btrim(p_reason),
           reversed_at = v_reversed_at
     where id = p_transaction_id;

    return v_reversed_at;
end;
$$;

create or replace function public.correct_transaction(
    p_original_id bigint,
    p_reason text,
    p_reseller_id bigint,
    p_type text,
    p_occurred_at timestamptz,
    p_observation text default null,
    p_item_id bigint default null,
    p_quantity integer default null,
    p_unit_price numeric default null,
    p_total_price numeric default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_original public.transactions%rowtype;
    v_replacement_id bigint;
    v_created_at timestamptz := clock_timestamp();
    v_item_name text;
    v_category_id bigint;
    v_category_name text;
    v_total numeric;
begin
    perform private.assert_easy_operator();

    if btrim(coalesce(p_reason, '')) = '' then
        raise exception using errcode = '22023', message = 'Informe o motivo da correção.';
    end if;

    if p_type not in ('order', 'payment', 'signal') then
        raise exception using errcode = '22023', message = 'Tipo de movimentação inválido.';
    end if;

    if p_occurred_at is null then
        raise exception using errcode = '22023', message = 'Informe uma data de ocorrência válida.';
    end if;

    select t.*
      into v_original
      from public.transactions t
     where t.id = p_original_id
     for update;

    if not found then
        raise exception using errcode = 'P0002', message = 'Lançamento não encontrado.';
    end if;

    if v_original.reversed_at is not null then
        raise exception using errcode = '23514', message = 'Este lançamento já foi estornado.';
    end if;

    if not exists (
        select 1 from public.resellers r
         where r.id = p_reseller_id
           and r.is_active
    ) then
        raise exception using errcode = '23503', message = 'Revendedor inexistente ou inativo.';
    end if;

    if p_type = 'order' then
        if p_item_id is null or p_quantity is null or p_quantity <= 0
           or p_unit_price is null or p_unit_price < 0
        then
            raise exception using errcode = '22023', message = 'Pedido corrigido requer item, quantidade positiva e preço unitário não negativo.';
        end if;

        if p_total_price is not null then
            raise exception using errcode = '22023', message = 'O total do pedido corrigido é calculado pelo servidor.';
        end if;

        if v_original.type = 'order' and v_original.item_id = p_item_id then
            if not exists (
                select 1 from public.items i
                 where i.id = p_item_id
                   and i.is_active
            ) then
                raise exception using errcode = '23503', message = 'Item inexistente ou inativo.';
            end if;

            v_item_name := v_original.item_name;
            v_category_id := v_original.category_id;
            v_category_name := v_original.category_name;
        else
            select i.name, i.category_id, c.name
              into v_item_name, v_category_id, v_category_name
              from public.items i
              join public.categories c on c.id = i.category_id
             where i.id = p_item_id
               and i.is_active
               and c.is_active;

            if not found then
                raise exception using errcode = '23503', message = 'Item inexistente, inativo ou sem categoria ativa.';
            end if;
        end if;

        v_total := p_quantity * p_unit_price;

        insert into public.transactions (
            reseller_id, type, item_id, item_name, quantity, unit_price,
            category_id, category_name, total_price, observation,
            replaces_transaction_id, occurred_at, created_at
        )
        values (
            p_reseller_id, p_type, p_item_id, v_item_name, p_quantity, p_unit_price,
            v_category_id, v_category_name, v_total, p_observation,
            p_original_id, p_occurred_at, v_created_at
        )
        returning id into v_replacement_id;
    else
        if p_item_id is not null or p_quantity is not null or p_unit_price is not null then
            raise exception using errcode = '22023', message = 'Pagamentos e sinais corrigidos não podem carregar campos de pedido.';
        end if;

        if p_total_price is null or p_total_price <= 0 then
            raise exception using errcode = '22023', message = 'Pagamento ou sinal corrigido requer valor positivo.';
        end if;

        insert into public.transactions (
            reseller_id, type, total_price, observation,
            replaces_transaction_id, occurred_at, created_at
        )
        values (
            p_reseller_id, p_type, p_total_price, p_observation,
            p_original_id, p_occurred_at, v_created_at
        )
        returning id into v_replacement_id;
    end if;

    update public.transactions
       set reversal_reason = btrim(p_reason),
           reversed_at = v_created_at,
           replacement_transaction_id = v_replacement_id
     where id = p_original_id;

    return v_replacement_id;
end;
$$;

revoke all on function public.create_transaction(bigint, text, timestamptz, text, bigint, integer, numeric, numeric) from public, anon;
revoke all on function public.reverse_transaction(bigint, text) from public, anon;
revoke all on function public.correct_transaction(bigint, text, bigint, text, timestamptz, text, bigint, integer, numeric, numeric) from public, anon;

grant execute on function public.create_transaction(bigint, text, timestamptz, text, bigint, integer, numeric, numeric) to authenticated;
grant execute on function public.reverse_transaction(bigint, text) to authenticated;
grant execute on function public.correct_transaction(bigint, text, bigint, text, timestamptz, text, bigint, integer, numeric, numeric) to authenticated;

comment on table public.easy_operators is 'Server-managed allow-list of Supabase Auth user UUIDs allowed to operate the Easy store.';
comment on table public.transactions is 'Canonical immutable financial movement rows. Browser direct DML is revoked; writes use controlled RPCs.';
comment on function public.correct_transaction(bigint, text, bigint, text, timestamptz, text, bigint, integer, numeric, numeric)
is 'D-013/D-026 atomic correction: insert linked replacement and reverse/link original in one PostgreSQL transaction.';
