create table public.manual_recovery_events (
    id bigint generated by default as identity primary key,
    event_type text not null,
    export_event_id bigint null,
    filename text null,
    actor_user_id uuid not null,
    created_at timestamptz not null default clock_timestamp(),
    constraint manual_recovery_event_type_valid check (event_type in ('export', 'confirm')),
    constraint manual_recovery_event_shape_valid check (
        (
            event_type = 'export'
            and export_event_id is null
            and filename is not null
            and btrim(filename) <> ''
        )
        or
        (
            event_type = 'confirm'
            and export_event_id is not null
            and filename is null
        )
    ),
    constraint manual_recovery_confirm_unique unique (export_event_id),
    constraint manual_recovery_export_event_fk
        foreign key (export_event_id)
        references public.manual_recovery_events(id)
        on update restrict on delete restrict
);

create index manual_recovery_events_created_at_idx
    on public.manual_recovery_events(created_at desc, id desc);
create index manual_recovery_events_actor_created_at_idx
    on public.manual_recovery_events(actor_user_id, created_at desc, id desc);

alter table public.manual_recovery_events enable row level security;

revoke all on table public.manual_recovery_events from public, anon, authenticated, service_role;
revoke all on sequence public.manual_recovery_events_id_seq from public, anon, authenticated, service_role;

grant select, insert on table public.manual_recovery_events to authenticated;
grant usage, select on sequence public.manual_recovery_events_id_seq to authenticated;

create policy manual_recovery_events_operator_select
on public.manual_recovery_events
for select
to authenticated
using ((select public.is_easy_operator()));

create policy manual_recovery_events_operator_insert
on public.manual_recovery_events
for insert
to authenticated
with check (
    (select public.is_easy_operator())
    and actor_user_id = (select auth.uid())
);

create or replace function private.prepare_manual_recovery_event()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_export_event_id bigint;
begin
    if (select auth.uid()) is null or not (select public.is_easy_operator()) then
        raise exception using
            errcode = '42501',
            message = 'Usuário não autorizado para registrar checkpoint manual do Easy.';
    end if;

    new.actor_user_id := (select auth.uid());
    new.created_at := clock_timestamp();

    if new.event_type = 'export' then
        if new.filename is null or btrim(new.filename) = '' then
            raise exception using
                errcode = '22023',
                message = 'Informe o nome do arquivo de backup exportado.';
        end if;

        new.filename := btrim(new.filename);
        new.export_event_id := null;
        return new;
    end if;

    if new.event_type = 'confirm' then
        select e.id
          into v_export_event_id
          from public.manual_recovery_events e
         where e.event_type = 'export'
           and e.actor_user_id = (select auth.uid())
           and not exists (
                select 1
                  from public.manual_recovery_events c
                 where c.event_type = 'confirm'
                   and c.export_event_id = e.id
           )
         order by e.created_at desc, e.id desc
         limit 1;

        if v_export_event_id is null then
            raise exception using
                errcode = '55000',
                message = 'Exporte um Backup v2 antes de confirmar a cópia manual global.';
        end if;

        new.export_event_id := v_export_event_id;
        new.filename := null;
        return new;
    end if;

    raise exception using
        errcode = '22023',
        message = 'Tipo de evento de recuperação inválido.';
end;
$$;

create trigger manual_recovery_events_prepare
before insert on public.manual_recovery_events
for each row execute function private.prepare_manual_recovery_event();

create or replace function public.get_manual_recovery_health()
returns table (
    last_exported_at timestamptz,
    last_filename text,
    confirmed_at timestamptz,
    pending_export_at timestamptz,
    pending_filename text
)
language plpgsql
stable
security invoker
set search_path = ''
as $$
begin
    if not (select public.is_easy_operator()) then
        raise exception using
            errcode = '42501',
            message = 'Usuário não autorizado para consultar recuperação do Easy.';
    end if;

    return query
    with latest_confirmed as (
        select
            e.created_at as exported_at,
            e.filename,
            c.created_at as confirmed_at
        from public.manual_recovery_events c
        join public.manual_recovery_events e
          on e.id = c.export_event_id
         and e.event_type = 'export'
        where c.event_type = 'confirm'
        order by e.created_at desc, e.id desc
        limit 1
    ),
    latest_pending as (
        select
            e.created_at as exported_at,
            e.filename
        from public.manual_recovery_events e
        where e.event_type = 'export'
          and e.actor_user_id = (select auth.uid())
          and not exists (
              select 1
              from public.manual_recovery_events c
              where c.event_type = 'confirm'
                and c.export_event_id = e.id
          )
        order by e.created_at desc, e.id desc
        limit 1
    )
    select
        (select lc.exported_at from latest_confirmed lc),
        (select lc.filename from latest_confirmed lc),
        (select lc.confirmed_at from latest_confirmed lc),
        (select lp.exported_at from latest_pending lp),
        (select lp.filename from latest_pending lp);
end;
$$;

create or replace function private.latest_manual_recovery_checkpoint_at()
returns timestamptz
language sql
stable
security invoker
set search_path = ''
as $$
    select max(e.created_at)
    from public.manual_recovery_events c
    join public.manual_recovery_events e
      on e.id = c.export_event_id
     and e.event_type = 'export'
    where c.event_type = 'confirm';
$$;

create or replace function private.manual_recovery_mode_initialized()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
    select exists (
        select 1
        from public.manual_recovery_events
        limit 1
    );
$$;

create or replace function private.manual_recovery_checkpoint_is_fresh_at(p_now timestamptz)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
    select coalesce(
        p_now < private.latest_manual_recovery_checkpoint_at() + interval '24 hours',
        false
    );
$$;

create or replace function private.assert_recovery_backup_fresh()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
    if private.is_direct_database_maintenance() then
        return;
    end if;

    if private.is_authorized_logical_restore() then
        return;
    end if;

    if private.automated_recovery_guard_enabled() then
        if not private.recovery_backup_is_fresh_at(clock_timestamp()) then
            raise exception using
                errcode = '55000',
                message = 'Business writes are blocked because verified off-site recovery evidence is missing, older than 24 hours, or retains fewer than 7 daily generations.';
        end if;
        return;
    end if;

    -- D-031 transition compatibility: an empty event table means the old browser
    -- candidate may continue operating until the first global checkpoint attempt.
    -- Once any global manual event exists, the server guard is permanently active.
    if not private.manual_recovery_mode_initialized() then
        return;
    end if;

    if not private.manual_recovery_checkpoint_is_fresh_at(clock_timestamp()) then
        raise exception using
            errcode = '55000',
            message = 'Cópia manual global ausente ou vencida. Exporte um novo Backup v2 e confirme que o arquivo foi guardado fora do Easy.';
    end if;
end;
$$;

revoke all on function private.prepare_manual_recovery_event() from public, anon, authenticated, service_role;
revoke all on function private.latest_manual_recovery_checkpoint_at() from public, anon, authenticated, service_role;
revoke all on function private.manual_recovery_mode_initialized() from public, anon, authenticated, service_role;
revoke all on function private.manual_recovery_checkpoint_is_fresh_at(timestamptz) from public, anon, authenticated, service_role;

revoke all on function public.get_manual_recovery_health() from public, anon, authenticated, service_role;
grant execute on function public.get_manual_recovery_health() to authenticated;

comment on table public.manual_recovery_events is 'Append-only D-031 operator-attested manual Backup v2 export/confirmation events shared across approved Easy operators and devices. This is not D-030 automated durability evidence.';
comment on function public.get_manual_recovery_health() is 'Returns the store-global confirmed manual checkpoint and the current operator pending export for D-031 early-use clients.';
comment on function private.manual_recovery_checkpoint_is_fresh_at(timestamptz) is 'D-031 global manual checkpoint predicate. A checkpoint is stale at the exact 24-hour boundary, matching the accepted browser fail-closed behavior.';
comment on function private.assert_recovery_backup_fresh() is 'Unified business-write recovery guard: D-030 automated evidence when enabled; otherwise initialized D-031 store-global manual checkpoint freshness.';
